[package]
name = "pg2parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
libpq = "4.0.0"

[package.metadata.scripts]
db_docker_up="docker compose up -d"
db_docker_down="docker compose down"
