version: '3'

services:
  postgres:
    image: postgres:16
    ports:
      - 5433:5432
    volumes:
      - ./docker/sql_setup.sh:/docker-entrypoint-initdb.d/sql_setup.sh
    environment:
      POSTGRES_PASSWORD: postgres
